Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : XXX
Info [interflop-verrou]: load backend with:
Info [interflop-verrou]: rounding-mode = UPWARD
Info [interflop-verrou]: seed = XXX
Info [interflop-verrou]: static-backend = false
Backend interflop-verrou : 1.x-dev
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                     3000                     2000          ( 67%)
  `- flt                     3000                     2000      ( 67%)
      `- llo                     3000                     2000  ( 67%)
 ---------------------------------------------------------------------
 sub                        3                        2          ( 67%)
  `- flt                        3                        2      ( 67%)
      `- llo                        3                        2  ( 67%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
