Verrou, Check floating-point rounding errors
Copyright (C) XXXXX 

First seed : 422
Info [interflop-verrou]: load backend with:
Info [interflop-verrou]: rounding-mode = RANDOM_DET
Info [interflop-verrou]: seed = 422
Info [interflop-verrou]: static-backend = false
Backend interflop-verrou : 1.x-dev
Instrumented operations :
	add : yes
	sub : yes
	mul : yes
	div : yes
	mAdd : yes
	mSub : yes
	cmp : no
	conv : yes
	max : no
	min : no
Instrumented vectorized operations :
	scal : no
	llo  : yes
	vec2  : yes
	vec4  : yes
	vec8  : yes
	unk  : yes
Instrumented type :
	flt : yes
	dbl : yes

 ---------------------------------------------------------------------
 Operation                            Instruction count
  `- Precision
      `- Vectorization          Total             Instrumented
 ---------------------------------------------------------------------
 add                   100001                   100000          (100%)
  `- flt                   100001                   100000      (100%)
      `- llo                   100001                   100000  (100%)
 ---------------------------------------------------------------------
 mul                        1                        0          (  0%)
  `- flt                        1                        0      (  0%)
      `- llo                        1                        0  (  0%)
 ---------------------------------------------------------------------
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
